Update run.sh
signalfx/docker-collectd pull request #48
Opened 2017-06-07 15:39 UTC by keitwb

2017-06-07 17:03 UTC, mjtieman approved these changes

2017-06-07 19:48 UTC, charliesignalfx commented on ubuntu/run.sh
> +specify a hostname with the option -e \"COLLECTD_HOSTNAME=<hostname>\" or by \
please make this change in the alpine run.sh script as well

2017-06-07 19:49 UTC, codesmith14 requested changes
Please add the same change to the alpine run script

2017-06-08 19:29 UTC, codesmith14 approved these changes

2017-06-08 19:29 UTC, merged